language: python
sudo: false
python:
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
env:
  - KOTTI_TEST_DB_STRING=sqlite://
before_install:
  - pip install codecov
install:
  - pip install -U tox
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov
