language: python
sudo: false
python:
- '3.6'
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
- KOTTI_TEST_DB_STRING=sqlite://
before_install:
- pip install codecov
install:
- pip install -U tox
- pip install tox-travis
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: davidemoro
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: Kotti/kotti_backend
  password:
    secure: YJlcKkUVMGwlTGv3qn9fV6im8F9Qw2FJsyg5KvG561jPzkpfvVPXBvbPoU+X3bC49pwWvdlOL7XOQIqGTNTxvY1OoMfhyILJaBNloOrLSyvms4UO8UDLrUEV9lb5JNy5JdTGnnJ+jOWLO89zUy+qgO7nM/xa0HXbsmgka7SrNE4OZpAkJjSExZM2EWuu8je7trdkWUYeaNXEeCROpTKAbOzYXo74gzmWOXNOr4Qk7SC+PndVIGRRR163qtwoRwCzaJ0bQbLRUroCM2mXdMzwYjHYuq4rYQdN4SVdBFZjTfrISPK9p1NT+2NUIpp8QAkrdtjsBsxBIRnkUf8erzLLt/+vsVtfvJnB88vJidoDj9wv8/lItZKjob4R/4DU4+tF6jXJ7uEJ1hUnvLfBK9wBZ4xnlXUo92DXtNWupydtLqA0AvJ93z8XRjbyZetfABK1cAwt+ZM70iMEDeDSq0h8wgEz+TKz//LbuA+MJA3hZK0tDTP2V/lZn1QBNGeVL7zztR5AfU49kJqzLigwgorP6J70fae9MaSj3PsJPUnFnL7EDuimU03YWnNoDam+YwC1kjLcsOMy2RCJfzSkertbVW7C/Y6RhR+w+usrngIpK7HlYPSrO1w1FU38cflOUlBh+n78uQ1rLRPfyP6I7kia6FRCCONrJsNEohTZj6iv+Xg=
